### ISSUE TITLE
关于汉化哪个版本

### ISSUE THREAD

**Issue by nobodxbodon** [program-in-chinese/CTS#5]
https://github.com/Microsoft/TypeScript/releases/tag/v2.5.3 好像是最近的正式发布版本吧?
https://github.com/Microsoft/TypeScript/releases/tag/v2.6-rc 是pre-release
不知为何选择2.7.0?

**Comment by htwx** [comment]
2.53 没有 汉化 编译错误 , 这2.7 是汉化了编译错误的,还有就是现在从2.7 写, 完成后他也就该发布稳定版了,他的稳定版一发,我们在做下适配就也能发了.

**Comment by nobodxbodon** [comment]
好. 希望到稳定版之前的改动不会太大. 追着官方跑会比较累. 最好找到一个尽量独立的汉化方式, 不过也许需要几次汉化之后才能总结出来.
